spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=user
spring.datasource.password=pass

app.services.post.url=http://localhost:8087
spring.kafka.bootstrap-servers=localhost:29092
