spring.application.name=auth-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/social_network}
spring.datasource.username=user
spring.datasource.password=pass

spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.schemas=auth
spring.flyway.default-schema=auth

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.access-ttl-minutes=15
app.jwt.refresh-ttl-days=7
app.jwt.issuer=auth-service

management.endpoints.web.exposure.include=health,info