version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sn_postgres
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - sn_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d social_network"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: sn_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - sn_redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: sn_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - sn_minio_data:/data

  auth-service:
    build:
      context: ../services/auth-service
    container_name: sn_auth_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/social_network
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

      APP_JWT_SECRET: ${APP_JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

  social-graph-service:
    build:
      context: ../services/social-graph-service
    container_name: sn_social_graph_service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/social_network
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  sn_pg_data:
  sn_redis_data:
  sn_minio_data: