spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=user
spring.datasource.password=pass

app.services.social-graph.url=http://localhost:8084
app.services.post.url=http://localhost:8087