server.port=8082
spring.application.name=feed-service

spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=user
spring.datasource.password=pass

spring.jpa.properties.hibernate.default_schema=feed
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.schemas=feed
spring.flyway.default-schema=feed