spring.application.name=social-graph-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/social_network
spring.datasource.username=user
spring.datasource.password=pass

spring.jpa.properties.hibernate.default_schema=social
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.schemas=social
spring.flyway.default-schema=social